apiVersion: apps/v1
kind: Deployment
metadata:
  name: vishal_myapp
spec:
  selector:
    matchLabels:
      app: vishal_myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: vishal_myapp
    spec:
      containers:
      - name: vishal_myapp
        image: vishal/argocd-app:1.3
        ports:
        - containerPort: 8080
